print("Welcome to COM411")
print("In week 1 we are going to learn\n")
print("How to use Git and GitHub")
print("How to output to the screen")
print("How to get user input\n")
print("I hope you are enjoying this lesson\n")
print("##########")
print("#        #")
print("#        #")
print("##########\n")
# Ask user to enter their name
print("What is your name?")
name = input()
print(f"It is nice to meet you {name}")
print(f"What eyes do you want for your robot?")
eye = input()
print("###########")
print(f"#  {eye}   {eye}  #")
print("#   ---   #")
print("###########")
